In [5]:

import numpy as np

In [ ]:
#To know more about this function execute:- >> help(np.linspace)

In [ ]:
#In linspace the numbers are evenly spaced.

In [6]:
# To create 10  floats between 1 and 10. By default the end point is included
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [7]:
#you can specify the 3rd argument as simply 10 or num=10 (Both are similar)
np.linspace(1,10,num=10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [8]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [10]:
#When end point is included
np.linspace(1,3,3,endpoint=True)

array([1., 2., 3.])

In [11]:
#When end point is not included
np.linspace(1,3,3,endpoint=False)

array([1.        , 1.66666667, 2.33333333])

In [15]:
#to see the different between numbers/step
np.linspace(1,11,5, retstep=True)

(array([ 1. ,  3.5,  6. ,  8.5, 11. ]), 2.5)

In [16]:
#To change the floating to integer we can have
np.linspace(1,10,10, dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
#If we just specify first and second parameter, we get 50 values as  num=50 (by default)
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])